name: Scratch
on:
  push:
  workflow_dispatch:
jobs:
  my-job:
    runs-on: windows-latest
    steps:
      - name: Update git for windows
        if: runner.os == 'Windows'
        run: git update-git-for-windows --yes
        shell: pwsh
