name: Scratch
on:
  push:
  workflow_dispatch:
jobs:
  my-job:
    runs-on: windows-latest
    steps:
      - run: |
          gcm -All git
          bash -c ps
          git --version
          gcm -All start
        shell: pwsh
      - run: |
          which start
          cat $(which start)
          which bash
          which sh
        shell: bash
      # - name: Update git for windows
      #   if: runner.os == 'Windows'
      #   run: |
      #     $git = (Get-Command git).Source
      #     Get-Process | Where-Object { $_.StartTime -ne $null } | Sort-Object StartTime -Descending
      #     $process = Start-Process -NoNewWindow -PassThru -FilePath $git -ArgumentList "update-git-for-windows","-y"
      #     Get-Process | Where-Object { $_.StartTime -ne $null } | Sort-Object StartTime -Descending
      #     $process.WaitForExit(90000)
      #     Get-Process | Where-Object { $_.StartTime -ne $null } | Sort-Object StartTime -Descending
      #     if (-not $process.HasExited) {
      #         Write-Output "Process did not exit within 90 seconds. Terminating."
      #         $process.Kill()
      #     } else {
      #         Write-Output "Process exited with code $($process.ExitCode)"
      #     }
      #   shell: pwsh
      #   env:
      #     GIT_TRACE: 1
      # - shell: pwsh
      #   if: always()
      #   run: |
      #     [Reflection.Assembly]::LoadWithPartialName("System.Drawing")
      #     function screenshot([Drawing.Rectangle]$bounds, $path) {
      #        $bmp = New-Object Drawing.Bitmap $bounds.width, $bounds.height
      #        $graphics = [Drawing.Graphics]::FromImage($bmp)
      #        $graphics.CopyFromScreen($bounds.Location, [Drawing.Point]::Empty, $bounds.size)
      #        $bmp.Save($path)
      #        $graphics.Dispose()
      #        $bmp.Dispose()
      #     }
      #     $bounds = [Drawing.Rectangle]::FromLTRB(0, 0, 1000, 900)
      #     screenshot $bounds "screenshot1.png"
      #     Start-Sleep -Seconds 90
      #     screenshot $bounds "screenshot2.png"
      # - if: always()
      #   run: |
      #     gcm -All git
      #     bash -c ps
      #     git --version
      #   shell: pwsh
      # - uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     path: .
