name: Scratch
on:
  push:
  workflow_dispatch:
jobs:
  my-job:
    runs-on: windows-latest
    steps:
      - name: Update git for windows
        if: runner.os == 'Windows'
        run: |
          gcm -All sh
          bash -c ps
          sh -x /mingw64/bin/git-update-git-for-windows -y
        shell: pwsh
        env:
          GIT_TRACE: 1
      - shell: pwsh
        if: always()
        run: |
          [Reflection.Assembly]::LoadWithPartialName("System.Drawing")
          function screenshot([Drawing.Rectangle]$bounds, $path) {
             $bmp = New-Object Drawing.Bitmap $bounds.width, $bounds.height
             $graphics = [Drawing.Graphics]::FromImage($bmp)
             $graphics.CopyFromScreen($bounds.Location, [Drawing.Point]::Empty, $bounds.size)
             $bmp.Save($path)
             $graphics.Dispose()
             $bmp.Dispose()
          }
          $bounds = [Drawing.Rectangle]::FromLTRB(0, 0, 1000, 900)
          screenshot $bounds "screenshot.png"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshot
          path: "screenshot.png"
